apiVersion: apps/v1
kind: Deployment

metadata:
  name: toolbox

spec:
  replicas: 1

  selector:
    matchLabels:
      app: toolbox

  template:
    metadata:
      labels:
        app: toolbox

    spec:
      containers:
        - name: toolbox
          image: ghcr.io/jawr/whois-bi/toolbox:latest
          command: ["sh", "-c", "tail -f /dev/null"]
          envFrom:
            - configMapRef:
                name: rabbitmq-env
            - configMapRef:
                name: postgres-env
