apiVersion: v1
kind: Service

metadata:
  name: api
  labels:
    app: api
    tier: frontend

spec:
  # for development on one node this is fine
  type: NodePort

  ports:
    - port: 80
      name: http

  selector:
    app: api
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deploy

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api
      tier: frontend

  template:
    metadata:
      labels:
        app: api
        tier: frontend

    spec:
      restartPolicy: Always

      containers:
        - name: api
          image: docker.io/whoisbi/api:latest

          ports:
            - containerPort: 80
              name: api

          envFrom:
            - configMapRef:
                name: postgres-env
