FROM golang:alpine

WORKDIR /test

COPY go.mod go.sum .
RUN go mod download

COPY . . 

ARG service
RUN CGO_ENABLED=0 go test -v -cover $service \
	| sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' \
	| sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
