name: release whois.bi
on:
  push:
    branches:
      - release

jobs:
  docker-build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: {context}/services/Dockerfile
          build-args: service=api
          tags: whoisbi/api:latest

  docker-build-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: {context}/services/Dockerfile
          build-args: service=manager
          tags: whoisbi/manager:latest

  docker-build-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: {context}/services/Dockerfile
          build-args: service=worker
          tags: whoisbi/worker:latest
