name: release whois.bi
on:
  push:
    branches:
      - master

jobs:
  docker-build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          file: ./build/service.dockerfile
          build-args: service=api
          tags: ghcr.io/jawr/whois-bi/api:latest

  docker-build-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          file: ./build/service.dockerfile
          build-args: service=manager
          tags: ghcr.io/jawr/whois-bi/manager:latest

  docker-build-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          file: ./build/service.dockerfile
          build-args: service=worker
          tags: ghcr.io/jawr/whois-bi/worker:latest
